### ISSUE TITLE
Quest Issue

### ISSUE THREAD

**Issue by Serenitygene** [Haggle1996/RevolutionPack#106] opened 2015-10-14 05:00 UTC
Agriculture quest "They Don't sting" will not register forest princess correctly, tried it with 8 different ones, pristine and ignoble both fresh from the hive and none have registered even with manual detect.

**Comment by Haggle1996** [comment] 2015-10-14 05:02
@Ieldra2 bees are a pain to detect -- if their alleles are even slightly different from the one you made, it will never register. You will probably need to broaden the detection.

**Comment by Ieldra2** [comment] 2015-10-14 21:19
That's why I explained in the text that they have to be fresh from the hive. That always did it in my tests. The problem is that precise detection will require all traits to match, while NBT-independent will make it so that any princess triggers completion. 
Anyway, I've changed the quest to require only one princess of any kind, but 4 drones of each of the two species.

**Comment by Haggle1996** [comment] 2015-10-15 23:35
Thanks, Ieldra. Closing.

**Closed by Haggle1996** 2015-10-15 23:35 UTC
