### ISSUE TITLE
gun customization missing textures and sounds on Linux

### ISSUE THREAD

**Issue by Toksyuryel** [Haggle1996/RevolutionPack#180] opened 2016-01-13 20:02 UTC
Something I didn't realize before when I mentioned this on the forum is that it appears about half of the textures are actually working in this version, in the previous alpha only one or two of them were, so something definitely changed between the two versions to fix many of them on my system. I'm gonna switch to creative mode and test out each item to see if some of them have sound and some of them don't, or if sound is broken for all of them.

![2016-01-13_11 58 48](https://cloud.githubusercontent.com/assets/1735640/12306046/99ba5e24-b9ec-11e5-90b8-4b8cbe299718.png)
[fml-client-latest.log.zip](https://github.com/Haggle1996/RevolutionPack/files/89426/fml-client-latest.log.zip)

**Comment by Toksyuryel** [comment] 2016-01-13 20:16
Ok yeah, the ones with working textures also have sound working correctly. The ones without textures are silent.

**Comment by AEnterprise** [comment] 2016-01-13 20:42
probably one of those capitalization errors, the capitalization of stuff in code doesn't match the file ones, for some reason that works in dev environments but not always outside them

**Comment by Haggle1996** [comment] 2016-01-15 00:02
All of those textures that are missing come out of the GunCus folder in your Revolution instance, rather than distributed as a mod. Since the items are present, it may be as simple as a case-sensitivity problem.

**Comment by Haggle1996** [comment] 2016-01-16 16:33
Are you still experiencing this problem?

**Comment by Toksyuryel** [comment] 2016-01-16 17:18
Yes I am still experiencing this problem. There doesn't seem to be a new update yet and I don't see any instructions to follow in here, so I'm a little confused by the question. Was I meant to try something and misunderstood the request?

**Comment by Haggle1996** [comment] 2016-01-16 17:37
Can you verify if your instance/GunCus folder has 270 files of around 1,761,751 bytes? Also, try a reinstall of the pack to see if that clears it up.

The missing textures from the screenshot all come from the instance/GunCus folder. I've verified the missing textures are in the download, so the issue is related to your system. It could be a problem with Linux, or simply that there's a permission issue on these files. I can't replicate the problem on my Ubuntu box, so I assume it's either on your end, or a nuance with your distro.

If it's a nuance with your distro, I'd like to track it down and see if I can account for it.

**Comment by Toksyuryel** [comment] 2016-01-16 18:00
I appear to have 270 files totalling 1,907,063 bytes under /GunCus. Let's see how that changes with a reinstall of the pack. I hope it's not a nuance with my distro, I'm using Gentoo so that could be very tough to track down if it is.

**Comment by Toksyuryel** [comment] 2016-01-16 18:03
Following reinstall I still have 270 files but the byte total has increased to 1,909,207. Let's see if those were the magical missing bytes!

**Comment by Toksyuryel** [comment] 2016-01-16 18:31
They were not the magical missing bytes :( I took a look through the files under that directory and noticed that none of the items that are working actually have files in there. It's just the WholyGunCustom pack stuff that's not working.

**Comment by Toksyuryel** [comment] 2016-01-17 18:47
Alright here's where I'm at now:

I looked through the fml-client-latest.log file and found the texture errors section. It lists the error as `unknown resourcepack type stuuupiiid.guncus.GunCusResourceLoader : GunCus resources` and I'd just been told to try looking through the code on the GunCus github so I thought I had a lead here. Unfortunately none of the source files is called GunCusResourceLoader and further none of the source files even reference anything called ResourceLoader. I went and unpacked the jar and it does have a GunCusResourceLoader.class file inside it, but it's mixed text and binary data so it's difficult to parse and I have no idea what I'm even looking at.

What should I be looking for?

**Comment by Aivech** [comment] 2016-01-18 03:32
Look in the GunCus custom configs and make sure the case matches.

**Comment by Solego** [comment] 2016-01-18 23:42
So I've got 305 items totalling 1.9MB in my GunCus folder, and I am getting the same issue.

**Comment by LemADEC** [comment] 2016-01-19 00:29
Most launchers won't delete the GunCus folder when you ask for reinstall. Please delete your whole guncus folder _manually_, then reinstall the pack, then provides the full logs.

**Comment by Toksyuryel** [comment] 2016-01-20 07:39
This is after nuking the entire instance and installing fresh.
[fml-client-latest.log.zip](https://github.com/Haggle1996/RevolutionPack/files/97091/fml-client-latest.log.zip)

**Comment by LemADEC** [comment] 2016-01-20 22:23
Looks like no textures are found.
Please try the following:
1- rename the pack folder from WholyGunCustom to wholyguncustom,
2- remove the Guncus/template folder,
3- start the game,
4- post the new logs and the result of "ls -l -R" of your guncus folder.

**Comment by Toksyuryel** [comment] 2016-01-21 05:35
After launching, the template directory was automatically recreated. The ls shown here is following that happening. Changing the name of the directory seems to have stopped it from finding the guns at all, and they were not added to my inventory. The `latest.log` is full of an error from this.
[fml-client-latest.log.zip](https://github.com/Haggle1996/RevolutionPack/files/98720/fml-client-latest.log.zip)
[latest.log.zip](https://github.com/Haggle1996/RevolutionPack/files/98721/latest.log.zip)
[list.zip](https://github.com/Haggle1996/RevolutionPack/files/98722/list.zip)

**Comment by LemADEC** [comment] 2016-01-21 09:56
Ok, so it's not a permission issue and it's not reproductible on Mac.
According to logs, all guns are loading under a different pack name (lower case version of the original) except for the shotgun SPAS-12 due to casing being mixed up.
Changing the pack name changed their item name so you loose them from your world save and starting inventory.

Can you confirm all textures and sounds are working except for the SPAS now?

To fix SPAS-12, go to GunCus/wholyguncustom/guns/SPAS-12.cfg and fix the casing in the following line (towards the end of the file):

```
S:Texture=SPAS12
```

As a temporary fix, please try to split the wholyguncustom folder in 2:
- a WholyGunCustom folder with the bullets and guns subfolder
- a wholyguncustom folder with the remaining folders lang, sounds, and textures, and the sounds.json file

I'll need a bit of time to find the best strategy to fix that issue.

**Comment by Haggle1996** [comment] 2016-01-21 14:24
Sorry, I neglected to point out some relevant details about my pack: I unzipped the WholyGunCustom jar you provided into the GunCus folder and ship that GunCus folder as part of the configuration zip file. This was done so I could tweak some of the weapons values, to balance them against the mobs in the pack. The pack automatically deletes the GunCus folder at each reinstall.

Weapons with hyphens in their name (there were just a couple, such as the SPAS-12; the rest of the weapons were fine) caused a texture load error on my dev box when the WholyGunCustom.jar was unzipped, so I removed the hyphens from all related files and configurations. This fixed the problem on Windows 10. I also do not experience the problem on my Ubuntu box.

**Comment by Toksyuryel** [comment] 2016-01-21 18:21
EVERYTHING WORKS :D Thanks so much, implementing all of those changes fixed everything.

**Comment by LemADEC** [comment] 2016-01-21 21:43
WholyGunCustom is a ZIP file that needs to be unzipped to work properly.
You're the first to report an issue with "-" in the texture names. I've Windows 10 and didn't experience such issue. What did you use to unpack that file?

**Comment by Haggle1996** [comment] 2016-01-21 22:50
My apologies, @LemADEC, I was confusing a different issue from another mod (too many bug reports to keep straight in my head). I removed the hyphen not because of a texture issue, but because I use MineTweaker to add guns to random dungeon chest loot. MineTweaker exploded on the guns with hyphens in the name, so I removed the hyphens and all was well. This is probably a Minetweaker bug not handling the hyphen properly, not an issue on your end.

**Comment by LemADEC** [comment] 2016-01-22 01:30
ok, thanks for the confirmation

**Comment by Haggle1996** [comment] 2016-01-30 15:59
The AT Launcher zip library appears to treat these two folders as the same, so I'm not sure how I can include a fix for linux users in the pack. I've marked this issue as containing a workaround and hopefully an update in the future will make the fix automatic for linux users. Closing the issue until then.

**Closed as completed by Haggle1996** 2016-01-30 15:59 UTC
Labels: contains workaround

**Comment by LemADEC** [comment] 2016-02-04 10:06
I've added a fix for that in next update. I couldn't reproduce it, so tell me how it goes.

**Comment by Haggle1996** [comment] 2016-02-04 15:38
Will do.
