### ISSUE TITLE
Wooden bucket issues and infinitive rivers

### ISSUE THREAD

**Issue by Shazuli** [Haggle1996/RevolutionPack#603] opened 2017-02-02 20:24 UTC
Hi!

The wooden bucket from the mod with same name has a few limitations when it comes to usage. You can't craft for example fresh water with water inside a wooden bucket from the mod "Pam's HarvestCraft", but if you instead move the contains from wood to the normal iron bucket you are able to do so. This is a thing MineTweaker can tweak I presume from my own experience.

You also can't pick up water from a flowing river while the iron bucket can. Now when I mention it;
a river never runs out of water while the infinitive spring has been disabled. So you can keep on picking up water while the lake below slowly gets depleted, not sure if its possible to do fix such a thing without have to contact the mod creator for a support update.
![bucket oak](https://cloud.githubusercontent.com/assets/9884180/22566882/fa456ed8-e98d-11e6-841c-0233348d7b57.png)

**Comment by Haggle1996** [comment] 2017-02-02 23:38
Unfortunately, neither mod is supported anymore.

Pam's is also not minetweaker-able. I'm going to close this since I can't really do much about it, though the issue is noted.

**Closed as completed by Haggle1996** 2017-02-02 23:38 UTC
