### ISSUE TITLE
arc furnace outputs 1 vanilla iron ore for 1 raw iron ore

### ISSUE THREAD

**Issue by Comata** [Haggle1996/RevolutionPack#350] opened 2016-03-25 01:00 UTC
Same Bug as with the blast furnace in a past vserion, the recipe shows 4 raw iron ore = 1 vanilla iron ore and when you put in a stack it will work as intended, but you can also input 1 raw iron ore and will get the 1 vanilla iron ore

tested on the digtobuild server 2.4.0.0 and SMP 2.4.0.0

**Comment by gwydion0917** [comment] 2016-03-28 17:53
I can confirm this is happening on my server as well.

**Comment by sapid** [comment] 2016-04-09 00:30
I couldn't reproduce this on 2.4 singleplayer with the Crude Blast Furnace. Recipe shows 8 chunks -> 1 iron ore, and that's how the furnace functions. Did you migrate from 2.3 or was this world started with a freshly downloaded 2.4 pack?

Can you pastebin the contents of scripts/ImmersiveEngineering.zs? This is the relevant line, specifically
https://github.com/Haggle1996/RevolutionPack/blob/revolution2/scripts/ImmersiveEngineering.zs#L75

**Comment by Toksyuryel** [comment] 2016-04-09 00:34
The blast furnace bug was in a prior version, this bug report is about the arc furnace.

**Comment by sapid** [comment] 2016-04-09 20:39
Ach. I really need to read titles better after opening tickets. I'll test later today.

**Comment by sapid** [comment] 2016-04-10 04:06
Reproduced. It does look like a similar matter to #244 so the fix is probably similar to the one that closed BluSunrize/ImmersiveEngineering#957.

**Comment by Haggle1996** [comment] 2016-04-15 00:44
Fixed in next update.

**Closed as completed by Haggle1996** 2016-04-15 00:44 UTC
