### ISSUE TITLE
AE2 Stuff Crystal Growth Chamber Vanishing on Placement

### ISSUE THREAD

**Issue by Pterodactlol** [Haggle1996/RevolutionPack#380] opened 2016-04-29 01:58 UTC
Read Title
Revolution version 2.5.1.1
I have now lost 2 crystal growth chambers and desire reimbursement

**Comment by Haggle1996** [comment] 2016-04-29 02:54
Duplicate of #376

**Closed as completed by Haggle1996** 2016-04-29 02:54 UTC
