### ISSUE TITLE
Rev 2 Crash

### ISSUE THREAD

**Issue by mrdomrocks** [Haggle1996/RevolutionPack#276] opened 2016-02-22 23:17 UTC
When you click on the required aspect in nei for thaumcraft recipe the whole game crashes to desktop.

**Comment by Haggle1996** [comment] 2016-02-22 23:57
I need a crash log, but probably a duplicate of #205.

You can find the crash log in your crash-logs folder inside your REVOLUTION|2 instance folder.

**Comment by mrdomrocks** [comment] 2016-02-23 00:05
Here is the crash log.

http://pastebin.com/V1EvaUYN

**Comment by Haggle1996** [comment] 2016-02-23 00:12
Was this an upgrade from a previous version of REVOLUTION?

If so, delete your \saves\NEI folder (this just clears the NEI cache).

**Comment by mrdomrocks** [comment] 2016-02-23 01:01
Yeah installed the latest beta this evening. Will remove the cache and update this thread.

**Comment by Haggle1996** [comment] 2016-02-25 21:29
Closing. Comment here again if you're still encountering the problem.

**Closed as completed by Haggle1996** 2016-02-25 21:29 UTC
