### ISSUE TITLE
villages, rockhounding mod worldgen and a large area around spawnpoint permanently chunkloaded

### ISSUE THREAD

**Issue by Elvenkindred** [Haggle1996/RevolutionPack#398] opened 2016-05-11 09:59 UTC
Visible via mapwriter 'loaded chunks' overlay. 
Not affected by /purgechunks command. 
256chunks around spawn loaded (16x16). 

All these additional chunks really add up for people in SP.

**Comment by Haggle1996** [comment] 2016-05-13 23:02
Reported to the author.

**Comment by Aivech** [comment] 2016-05-14 12:52
This looks like it drastically expanded vanilla spawn chunkloading, for reasons unknown.

**Comment by Haggle1996** [comment] 2016-05-14 13:20
Just so you know, the 16x16 area of loaded chunks around spawn is the [vanilla mechanic](http://minecraft.gamepedia.com/Spawn_chunk) and can't be turned off, so that's not a bug. Villages are chunk loaded by enviromine; however, they use the same minimal load set as the 16x16 spawn area.

Guru huts also appear to be chunkloading under the same rules, so it seems they are also considered villages.

Loaded chunks are not expensive per se in Minecraft. 5,000 loaded empty chunks (no machines, normal mob spawns) don't have a particularly big impact on most gaming machines. If you load up the Opis mod and profile, you'll get a measurement of just how much these loaded chunks are impacting performance. On the dev server, it's not uncommon to have 6-8,000 loaded chunks, with TPS hovering in the 15-18ms range (that's really good, but the dev server is a beast).

Note, if you're using a utility like OptiFine, you can set it to load chunks way beyond the standard 10x10 area focused over the player, and this will have a big negative impact on your gameplay.

For now, I'm closing this, as I don't consider this a big problem; the engine is working as designed and the few extra hundred chunks loaded by villages just don't cause a big deal on any of my boxes.

**Closed as completed by Haggle1996** 2016-05-14 13:20 UTC
Labels: mod bug
