### ISSUE TITLE
Arc Furnace recipes for Vibrant Alloy do not work.

### ISSUE THREAD

**Issue by Kreidos** [Haggle1996/RevolutionPack#416] opened 2016-05-17 02:10 UTC
The Arc Furnace recipes for Vibrant alloy will only produce Energetic Alloy.

It seems when IE looks for matching recipes it stops at the first entry it finds in the recipe table. Since the recipe for Vibrant also includes the ingredients for Energetic, it will produce this instead since it comes first in the recipe list. The recipe using gold dust simply produces gold ingots; same logic applies.

**Comment by Haggle1996** [comment] 2016-05-17 02:53
BluSunrize/ImmersiveEngineering#843

**Comment by Kreidos** [comment] 2016-05-17 03:00
I have a fix ready if we want it right now.

By adjusting the order of recipes in the minetweaker script it will work just fine.

**Comment by Kreidos** [comment] 2016-05-17 03:07
This also fixes the Dust-based recipes, like the Conductive recipe which also doesn't work; though nobody seemed to mention that in the bug report.

**Comment by devanchya** [comment] 2016-05-17 17:51
Patch is based on an earlier version of the Script file. It does work but  I had to merge conflict fix it with latest in testing.

**Comment by Haggle1996** [comment] 2016-05-17 18:12
The problem is actually caused by my minetweaker script which breaks the new recipe. I'll fix it in the next update.

**Comment by Haggle1996** [comment] 2016-05-22 18:52
Fixed in the next update.

**Closed as completed by Haggle1996** 2016-05-22 18:52 UTC
