### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by fwsGonzo** [Haggle1996/RevolutionPack#192] opened 2016-01-30 16:29 UTC
Probably not modpack related, but who knows

```
[17:24:34] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeHi(TimSort.java:899) ~[?:1.8.0_60]
    at java.util.TimSort.mergeAt(TimSort.java:516) ~[?:1.8.0_60]
    at java.util.TimSort.mergeCollapse(TimSort.java:441) ~[?:1.8.0_60]
    at java.util.TimSort.sort(TimSort.java:245) ~[?:1.8.0_60]
    at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_60]
    at java.util.ArrayList.sort(ArrayList.java:1454) ~[?:1.8.0_60]
    at java.util.Collections.sort(Collections.java:175) ~[?:1.8.0_60]
    at com.draco18s.wildlife.entity.ai.EntityAIGetAttackableTarget.func_75250_a(EntityAIGetAttackableTarget.java:73) ~[EntityAIGetAttackableTarget.class:?]
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:70) ~[uj.class:?]
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:537) ~[sw.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774) ~[sv.class:?]
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367) ~[sw.class:?]
    at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25) ~[yg.class:?]
    at com.draco18s.wildlife.entity.EntityLizard.func_70636_d(EntityLizard.java:240) ~[EntityLizard.class:?]
```

The entity was probably saved when the server shutdown due to the error, and now it won't start.

**Comment by Haggle1996** [comment] 2016-01-30 16:37
Seems like a potential duplicate of #185, although it could be a corrupted entity too. Is this happening on startup? If so, does reverting to a previous save fix the problem? Also, if you can please post the full crash log to pastebin or gist, that would be very helpful.

**Comment by fwsGonzo** [comment] 2016-01-30 17:24
The crash is from a lizard spawning somewhere.. no desert where I was, except perhaps at the very edge of my location (within 10 chunks). This is because the lizards should only spawn in the desert... I think.
https://gist.github.com/fwsGonzo/74afc2a263621e95f509

Reverting to a previous save would help, sure, but I'd rather just remove the lizard .. but then I have to reboot into wintendo :(
I'm actually pretty convinced the crash is just rare

**Comment by fwsGonzo** [comment] 2016-01-30 17:36
Ok, I just removed all the hostile mobs with /cofh killall from server console:

```
cofh killall
[18:32:50] [Server thread/INFO]: Removed 54 hostile mobs. (§c6§fx§eSkeleton§f, §c1§fx§eenderzoo.WitherWitch§f, §c11§fx§eHarderWildlife.Lizard§f, §c1§fx§eWitch§f, §c1§fx§eetfuturum.villager_zombie§f, §c4§fx§eCreeper§f, §c1§fx§eEnderman§f, §c29§fx§eZombie§f)
```

And I can join the world again, everything works etc.
:+1:

**Comment by Haggle1996** [comment] 2016-01-30 18:00
Glad to hear it. Closing the issue.

**Closed as completed by Haggle1996** 2016-01-30 18:00 UTC

**Comment by fwsGonzo** [comment] 2016-01-30 18:14
It happened again, so I disabled lizards.

**Comment by Haggle1996** [comment] 2016-01-30 18:31
Okay. Let me know if it goes away without lizards. I may have to disable them permanently.

**Comment by fwsGonzo** [comment] 2016-01-30 20:05
It's been working very well since.. The lizards were pretty nice though, as they made the desert a little bit hostile (sand is valuable too!)

Very unfortunate
