### ISSUE TITLE
Chromaticraft Crystal Bees Failing To Get Special "Product"

### ISSUE THREAD

**Issue by ghost** [Haggle1996/RevolutionPack#448] opened 2016-06-03 05:03 UTC
I've been trying to make a crystal bee setup for all 16 bees, however no matter what I did all they would produce was normal honey combs. I did have all the requirements (and the progress relevant for some dusts).

I tested with a v14b instance and the exact same setup re-created worked. 

I'm guessing it's a bug in v13b from Reika's side but for all I know it could be a weird conflict or something.

**Comment by Haggle1996** [comment] 2016-06-03 21:27
Duplicate of #447

**Closed as completed by Haggle1996** 2016-06-03 21:27 UTC
Labels: duplicate

**Comment by ghost** [comment] 2016-06-05 02:47
@Haggle1996 It seems the update didn't fix this. I'm beginning to think a conflict or something is causing it.

 Going to investigate farther.

**Comment by Haggle1996** [comment] 2016-06-05 03:42
Please read your lexicon again carefully. You've missed something.

We have multiple players making the special products in v13.

**Comment by ghost** [comment] 2016-06-05 04:37
I copied the exact same setup onto another pack and it worked. The only different thing was progress however I have enough for it to work.

I have screenshots of the setup (top two are Rev2 and bottom two are another pack) [http://imgur.com/ygC6w2d&W2rQOyE&oYXFfrY&c9YP6ix](imgur.com/ygC6w2d) 
Note: the first has industrial apiarys although I didn't have a screenshot. 2nd and 3rd are the genes and fourth is the one I copied from the rev2 pack to see if it works.

I tried doing /chromaprog maximize all on another world for rev2 with the industrial apiary setup and nothing happened.

**Comment by Haggle1996** [comment] 2016-06-05 04:48
Just looking at the top two pictures, I can tell you've already made at least two mistakes. Regardless, this is not a pack issue. You should be discussing it on Reika's forum on MCF.

**Comment by ghost** [comment] 2016-06-05 08:04
Would you mind telling me what those two mistakes are, please?
