### ISSUE TITLE
Rockhounding silver dust does not cook.

### ISSUE THREAD

**Issue by romanticjo** [Haggle1996/RevolutionPack#371] opened 2016-04-21 03:45 UTC
Looks like there is a missing recipe to cook from silver dust to ingot.  

Tiny dust can cook to nugget, which can be combined into ingots.

**Comment by Haggle1996** [comment] 2016-04-21 05:39
Duplicate of #367

**Closed as completed by Haggle1996** 2016-04-21 05:39 UTC
Labels: duplicate

**Comment by OmegaCenti** [comment] 2016-04-21 05:41
I tested a patch I made on a single player and it appears to have fixed it. I submitted pull request #372 OmegaCenti:silver_smelting_patch
https://github.com/Haggle1996/RevolutionPack/pull/372/commits/35516c1ddeef1212f2ba0e78a7778e5e3f86de28
