### ISSUE TITLE
Stacks On Stacks

### ISSUE THREAD

**Issue by mtesseracttech** [Haggle1996/RevolutionPack#359] opened 2016-04-09 23:29 UTC
Quite a few items which are stackable using Stacks on stacks have problems, they either: Can be stacked while they should not be stacked (Automagy crystals), cannot be stacked while it would be nice to stack them (RoC alu/conductive alloy ingots) or don't have their proper colors (all RoC ingots).
There are also some items that can be stacked, but they don't show up at all when put on stacks (CrC crystals for example).

**Comment by Haggle1996** [comment] 2016-04-23 00:04
Duplicate of #339

**Closed as completed by Haggle1996** 2016-04-23 00:04 UTC
Labels: duplicate
