### ISSUE TITLE
Techguns mobs TPS issue (3.6.1, SSP)

### ISSUE THREAD

**Issue by happy2pester** [Haggle1996/RevolutionPack#630] opened 2017-03-23 14:34 UTC
My game, with the world in it's current state, gets a full 20 TPS in daylight or on peaceful mode.

However, when Techguns mobs start spawning, and if for whatever reason, those mobs cannot pathfind to the player, the average TPS on my world drops to 4.5

I've confirmed this through solid walls, et futurum fences and minecraft oak fences. 

I also temporarilly disabled techguns and confirmed that it was only techguns mobs that have this issue. Vanilla mobs caused no such TPS drops even when they could not pathfind to me.

Other people have also started reporting similar TPS issues when techguns mobs are about.

**Comment by Haggle1996** [comment] 2017-03-23 15:05
Thanks for narrowing this down for me. I'll get Techguns rolled back and a 3.6.2 released soon.

**Comment by Haggle1996** [comment] 2017-03-23 15:14
Version 3.6.2 is on the launcher, with the rolled back TechGuns mod

**Comment by Kannei** [comment] 2017-03-23 16:02
This does not fix the tps/tps issue on old maps however. As setting the world to pecefull was tested on Gwyndions server. Its helped, but just a little, only cus of less entitys to handle. And fps did not improove at all.
Not that i can tell what it is (aside from maybe retaining old data accumelation in blocks on mod updates) but ive noticed that fps issues is worse in areas with higher amount of Rotary and/or Rector craft blocks. So it seems that its something affecting  RoC/ReC blocks. Since thouse 2 mods wasnt updated, its not the mods itself. Also its affecting areas with high amounts of entitys like rainbow forests.

**Comment by happy2pester** [comment] 2017-03-23 16:52
A high amount of entities is always going to affect TPS. And larger/older maps with much more things going on are always going to have a worse TPS, but this was a fairly lethal TPS drop on a relitavely new world. I haven't done any CrC/RoC/ReC work. In terms of other things, i've got a single watermill and a wire stretching maybe thirty blocks to power a furnace heater, and a tiny bit of botania.

On SSP with 6 gigs of memory, i tested it thoroughly. Techguns mobs were at least one source of major TPS dropping.

**Comment by Kannei** [comment] 2017-03-23 17:07
AS a perspective. on 3.5.0 I got some 10 fps in the village base and some 20 ( I think) in rainbow forests with manny entitys in. and tps on the server (Gwyndions's) was 20 with 1 person online.
 
after the 3.6.0 update, also 3.6.1, the server tps dropped to 3 with 1 person online, part of that was due to a solar tower, disabeling that raised TPS to some 5-6. Even with Setting the server to peacefull only got an TPS improovement of 2. And my FPS in the village is 1-2 and in the rianbow forest its 1-5. But Bases with little to no Rotary in them I have 0 FPS issues.

**Comment by Haggle1996** [comment] 2017-03-23 19:09
Any improvement with 3.6.2?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ztw6969** [comment] 2017-03-23 19:39
Wow I can definitely confirm the OP ;) I experienced it multiple times in a row : a SINGLE tech gun mob pathes to me, and my TPS quickly drops to 5 (from 20), and as soon as I kill it, boom 20 TPS again.
In 3.6.2 yea.
Also the FPS problem isnt fixed either for me, I have 1/2 to 1/3 of the FPS I have in 1.5.0 (and 3 FPS with spawning overlay). Back to this version it is ;)

**Comment by Kannei** [comment] 2017-03-24 00:54
OK so regarding the genneral low tps issue  (that HAggle closed the issue thread on) it seems that the core mod for streams: Farseek is the cause for the overall and tech guns isse. Dont know how or why, but by reverting the farseek version to that in 3.5.0 i get 0 issues tps wise. i hope this also fixes fps too.
tested this on v3.6.0 first without changing anything, then with reverting farseek. and tps went from lower then 5 to 20 (30-40ms response time) on a small single player creative world with ReC Reactors testing settups and a solar tower.

**Comment by Haggle1996** [comment] 2017-03-24 01:02
I'm try to push this tomorrow morning

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Sekkys** [comment] 2017-03-25 05:33
Just commenting that on 3.6.2 I get well under 10 FPS in an open desert with nothing else around. It does seem to fix the TPS issue partially, but my FPS seems to suffer greatly. In 3.5 however, I am easily hitting 100+ FPS in my base with automation WITH Sonic Ether's shaders on a computer that is well and fully capable. So while I cannot confirm exactly what it is, for me the FPS issue was non existent in 3.5 and occurred sometime after that.

**Comment by Haggle1996** [comment] 2017-03-27 02:03
3.6.3 is on the launcher, which reverts Farseek, but restores the update to Techguns, as well as restoring Zombie Awareness and Special AI.

**Comment by Sekkys** [comment] 2017-03-27 03:09
I can't speak for TPS because I've only been in SP so far without much automation, but my FPS definitely improved, so the Farseek revert definitely seemed to fix the issue on my end.

**Comment by Haggle1996** [comment] 2017-03-29 06:11
Seems to be good. Closing the issue.

**Closed as completed by Haggle1996** 2017-03-29 06:11 UTC
