### ISSUE TITLE
Extra Utils Chandelier Throwing a Server Error

### ISSUE THREAD

**Issue by tbeebe** [Haggle1996/RevolutionPack#92] opened 2015-09-09 13:27 UTC
I get a series of these occasionally in the error log, it doesn't seem to be causing any problems but I don't know if there is an easy way to fix it. 

[09:22:05] [Server thread/ERROR] [FML]: A TileEntity type com.rwtema.extrautils.tileentity.TileEntityAntiMobTorch has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.rwtema.extrautils.tileentity.TileEntityAntiMobTorch is missing a mapping! This is a bug!
        at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:343) [ms.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:165) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by Haggle1996** [comment] 2015-09-12 11:38
I can't reproduce this one in any of my environments, yet. I did place a few so I can watch the logs. Have you tried breaking and replacing all your chandeliers? Sometimes there's just some bad block info sharing a square.

**Comment by Haggle1996** [comment] 2015-10-01 00:47
Closing, since I can't replicate and haven't had any feedback.

**Closed by Haggle1996** 2015-10-01 00:47 UTC
